### ISSUE TITLE
JSON root types

### ISSUE THREAD

**Issue by darobin** [darobin/formic#1]
Currently we only support JSON objects at the root, which seems sufficient. But JSON can also support other root types. Are there strong use cases to add support for these (knowing that it would likely complicate matters a fair bit).

**Comment by darobin** [comment]
No requests for anything else, feedback is that it's enough.

**Comment by sheavalentine-mdsol** [comment]
While I see this is closed, it strikes me that this is actually an issue. The spec doesn't seem to have a method for creating:

``` json
[
{"object": 1},
{"object": 2},
{"object": 3},
]
```

The best workaround seems to be:

``` json
{
"0": {"object": 1},
"1": {"object": 2},
"2": {"object": 3},
}
```

Which is hardly friendly.

Couldn't it support:

``` html
<input name="[][object]"> 
```

?

Though that does run into the problem of how one would interpret:

``` html
<input name="[][object]"> 
<input name="[person][]"> 
```
