### ISSUE TITLE
Complicated Value Retrieval

### ISSUE THREAD

**Issue by rodneyrehm** [darobin/formic#12]
As a receiver I can never know if a given data point is a string, an array or an object. Because you _never_ trust incoming data, You'd have to type-check everything.

``` html
<input name="mix" value="the-value">
<!-- { mix: "the-value" } -->

<input name="mix" value="default-value">
<input name="mix" value="the-value">
<!-- { mix: ["default-value", "the-value"] } -->

<input name="mix" value="the-value">
<input name="mix[0]" value="nested-value">
<!-- { mix: {"": "the-value", "0": "nested-value"} } -->
```

To retrieve `"the-value"` from `mix` properly, my reader would have to do the following:

``` js
var mix;
if (typeof data.mix === "string") {
    mix = data.mix;
} else if (Array.isArray(data.mix) && data.mix.length) {
    mix = data.mix[data.mix.length -1];
} else if (typeof data.mix === "object" && "" in data.mix) {
    mix = data.mix[""];
}
console.log("the value of mix", mix);
```

Combine that with the thought of having to destructure the generated JSON for _Example 6: Such Deep_ and you made absolutely sure that any data sent _has_ to be accessed through a "middleware" component.

**Comment by darobin** [comment]
No, you don't need a middleware component. You should, however, _validate_ your data.

The code you exemplify above isn't defensive access, it's mixing the validation and access concerns. It's as if you checked that your input is a number between 17 and 42 every time you accessed it.

JSON can even be checked with JSON Schema (or nicer variants) which in turn can be used to generate forms. Whatever is used, data constraints should be checked before and independently of data access.
