### ISSUE TITLE
Empty-String As Key

### ISSUE THREAD

**Issue by rodneyrehm** [darobin/formic#14]
I can't find the words to provide a proper argument and I can't think of a better solution, either. Using the empty-string as a key simply looks like a _hack_

``` html
<input name="mix" value="alpha">
<input name="mix[er]" value="bravo">
<!--
  { mix: {"": "alpha", "er": "bravo"} }
  mix=alpha&mix[er]=bravo
-->
```

**Comment by darobin** [comment]
It doesn't look like a hack to me :) I think there's a general issue about whether the whole data should be kept or not. If not, this likely just goes away. But if we keep it, I think it's the best solution.

I'm closing this and assuming that the "encode everything" discussion is in #16.

**Comment by macek** [comment]
Chiming in here to agree with with the `""` key as a non-hack.

I think the decision to avoid losing data is a good one. I think the argument can be as simple as, if you don't want a "hacked" JSON submission, don't build forms that would cause this kind of result.
