### ISSUE TITLE
File Upload can be a memory problem

### ISSUE THREAD

**Issue by rodneyrehm** [darobin/formic#17]
Inlining files like that may work if the files are small enough to fit into available buffers. The specification does not mention the words "asynchronous" and "streaming". Therefore I assume that a file
1. has to be read to memory as a whole,
2. transformed to base64 encoding in memory, 
3. pushed onto the composing data model in memory,
4. has it's memory released after the composing data model was serialized to string.

("in memory" can also mean "in memory file", "swapping", "whatever an implementor does to deal with scalable memory demand")

Being the naive type, I'd assume validating preconditions (exists, read-permissions, …) are done where the spec says, but actually reading, converting and pushing the file is done in step 4. This would assume that the serialized data is written directly onto network buffers and flushed appropriately.

The short question is what happens If I were to upload a 100MB file:
1. will my browser need to allocate 100+ MB of memory?
2. will the serialization block the event queue, making my UI unresponsive (when submitting into an iframe, which is common practice for file uploads)?

**Comment by darobin** [comment]
This is all stuff that's already an issue with form submission today, and that browsers handle already for other encodings.

What the specification describes is the black box behaviour. But I would fully expect implementations to stream the files' base64 straight to the wire without at all ever loading the file into memory or base64-encoding it there. The alternative would make for a pretty naïve implementation!
