### ISSUE TITLE
Note on supported HTTP methods.

### ISSUE THREAD

**Issue by lovelydinosaur** [darobin/formic#28]
Although the issue of HTTP methods supported by form submission is strictly speaking, orthogonal to the encoding of the request, it would be worth having this document at least making a note of the current status of support for HTTP methods in form submission.

It's likely that introduction of this encoding would lead to users expecting to be able to make JSON encoded `PUT` requests, so it'd be helpful if the document noted that JSON ecnodings will _always_ besent as `POST` requests.

Also what is the behavior if the "method" attribute _is_ present on the form? Should it always be silently ignored and treated as `POST`?

**Comment by darobin** [comment]
Have you given further thought to how the default behaviour of `PUT` would manifest itself in the browser?

**Comment by lovelydinosaur** [comment]
> Have you given further thought to how the default behaviour of PUT would manifest itself in the browser?

I'll raise that in a different context at some point.

Given that browsers _don't_ currently support `PUT` requests I simply think it'd make sense to note that the HTTP method is currently restricted to `POST` requests. (It's not _directly_ part of your work of course, but it is likely to be a relevant note for devs)
