### ISSUE TITLE
Wrong comment in spec

### ISSUE THREAD

**Issue by homeworkprod** [darobin/formic#32]
I noticed a bad comment in a JSON example at http://www.w3.org/TR/html-json-forms/, but it turned out this has already been fixed in 0d2a388dd.

As it would've saved at least me some irritation as well as time to look through this repo, I suggest to update the published spec document.

**Comment by darobin** [comment]
Sorry about that. The document will move to https://specs.webplatform.org/ and we are setting up automated publishing to avoid this sort of issue.

**Comment by homeworkprod** [comment]
Thanks.
