### ISSUE TITLE
JSON Submission parse in JavaScript

### ISSUE THREAD

**Issue by windyGex** [darobin/formic#34]
well, see the code below:

``` javascript
a['b']
a[b]
```

The first `b` is a string, but the second is a variable.
And as the rule of JSON Submission, `b` should be a string.
This error will effect implementation in javascript possible.

**Comment by darobin** [comment]
I'm sorry, I don't understand what you are trying to convey. Which part of the specification are you talking about?

**Comment by windyGex** [comment]
well, I want to know why not wrap b using quote? Recently, I want to implement the JSON Form, use my mvvm framework, but in my mvvm framework, when parse string， will think `b` is a variable, `'b'` is a string, this will cause parse error, so I want to know this.

**Comment by darobin** [comment]
But the syntax in name fields is not JS, it's just the syntax to specify keys.

**Comment by windyGex** [comment]
ok, I get it.
