### ISSUE TITLE
Is append needed?

### ISSUE THREAD

**Issue by darobin** [darobin/formic#4]
We have an "append" construct (`foo[]`) that is used for cases in which the developer wishes to indicate that even if there is only one instance of a given field name it should nevertheless be captured as an array. It is possible to achieve the same effect by carefully generating array indices, though it is slightly cumbersome. The feature is not costly in complexity, but given that it basically desugars to arrays it could be dropped with no loss of functionality.

**Comment by darobin** [comment]
Feedback is that this is indeed useful.

**Comment by macek** [comment]
:+1:  for "append" construct
