### ISSUE TITLE
Boolean radio/checkbox

### ISSUE THREAD

**Issue by darobin** [darobin/formic#5]
With the current algorithm, radio and checkbox inputs that are checked and have no `value` set are represented in JSON using a boolean `true` value instead of the `on` string used in other encodings. This seems like a better fit for a new encoding, but the departure from tradition may surprise some. (Note that unchecked inputs will still be absent, not `false`.)

**Comment by darobin** [comment]
Feedback is positive about this idea.

**Comment by macek** [comment]
@darobin, just to be clear, a checkbox input with a `value` attribute will be encoded with the value? Only ones without a `value` attribute will get true/false?

``` html
<form enctype='application/json'>
  <input type='checkbox' name='shiny' value='okay' checked>
</form>
```

Would be encoded as

``` js
{
    "shiny": "okay"
}
```

Correct?
