### ISSUE TITLE
Key/vals vs named values?

### ISSUE THREAD

**Issue by inadarei** [darobin/formic#9]
Disclaimer: I have no strong opinion either way and am not advocating one approach over the other, just very curious about the thought process used. Assuming others may want to know as well.

Robin, I was wondering if you have considered serializing form values as:

``` json
{
  "name" : {"value" : "Bender"}
, "hind"   : {"value" : "Bitable"}
, "shiny" : {"value" : true}
}
```

instead of 

``` json
{
  "name":   "Bender"
, "hind":   "Bitable"
, "shiny":  true
}
```

the arguable benefit being: extensibility. With the alternative format, you could do things like:

``` json
{
"born" : {"type" : "date", "value" : "..." }
}
```

**Comment by ioseb** [comment]
@inadarei +1 for extensible format!

**Comment by darobin** [comment]
It's not necessarily a bad idea per se, but it suffers from the problem that it immediately precludes the ability to address existing JSON services that won't be expecting that encoding.

Also, it's more verbose, and requires every data access on the server to then add .value. Overall it doesn't seem like a win. If you want to have that format, you _can_ support it just with foo[value] on every field.

Note that it isn't truly more extensible than the current encoding: there are other ways of extending the encoding. Also, you get nasty cases like inputs name foo and foo[value] — what happens there?

Overall I don't think that what it costs justifies what we lose.
